"""
module_5 program_1

Write a program that asks the user how many dice to roll. 
The program rolls all the dice once and prints out the sum of the numbers. 
Use a for loop.
"""
import random  # importing random modules 

#============================
# user-derfine function 
#============================
def total_sum(sum):    # defining user defined function
    roll_value=random.randint(1,6)  #rolling dices and assigning the result to variable
    print(f' The values generated each roll :: {roll_value}') # printing each value generated by each roll
    sum+=roll_value # adding the value to sum
    return sum      # returning the total sum 

#========================================== 
# Main program where number of dices to roll asked and pass to function calling 
#==========================================
sum=0   # initializing sum variable to zero 
number_dice=int(input('How many dices to roll? '))  # asking from user number of dices to roll
for roll in range(number_dice):  # for loop to using the dices.
    sum=total_sum(sum)          #calling user defined function and assigning the result to sum
print(f'The sum of rolling {number_dice} dices is :: {sum}') #displaying total dices and their sum 
    
    